# $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  nerdFontsVersion: "3"
  tabWidth: 2
  portraitModeAutoMaxWidth: 120
  mouseEvents: false
  # expandFocusedSidePanel: true
os:
  edit: '{ [ -z "$NVIM" ] && nvim -- {{filename}}; } || { nvim --server "$NVIM" --remote-send "<C-x>" && nvim --server "$NVIM" --remote {{filename}}; }'
  editAtLine: '{ [ -z "$NVIM" ] && nvim +{{line}} -- {{filename}}; } || { nvim --server "$NVIM" --remote-send "<C-x>" && nvim --server "$NVIM" --remote {{filename}} && nvim --server "$NVIM" --remote-send ":{{line}}<CR>"; }'
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
  openDirInEditor: '{ [ -z "$NVIM" ] && nvim -- {{dir}}; } || { nvim --server "$NVIM" --remote-send "<C-x>" && nvim --server "$NVIM" --remote-tab {{dir}}; }'
  editInTerminal: false
git:
  mainBranches:
    - main
    - release/*
  pagers:
    - externalDiffCommand: difft --color=always --syntax-highlight=on --tab-width=2
    - pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
customCommands:
  - key: t
    command: tig show {{.SelectedSubCommit.Sha}}
    context: subCommits
    description: tig commit (`t` again to browse files at revision)
  - key: t
    command: tig show {{.SelectedLocalBranch.Name}}
    context: localBranches
    description: tig branch (`t` again to browse files at revision)
  - key: t
    command: tig show {{.SelectedRemoteBranch.RemoteName}}/{{.SelectedRemoteBranch.Name}}
    context: remoteBranches
    description: tig branch (`t` again to browse files at revision)
